Implement network client and use tool window
turovkv/jetbrains-ide-features-gamification pull request #10
Opened 2021-05-20 23:17 UTC by turovkv

2021-05-22 08:54 UTC, bibaev requested changes
Предлагаю все-таки избегать названия веток таких как `plugin-dev`. С ними неудобно искать изменения и легко забыть, что именно хочется получить в этой ветки и менять в ней всё подряд :) Еще хорошая практика сослаться на себя в названии ветки. Например, `katya/add-tool-window`, либо `kirill/server-integration`.

2021-05-22 08:54 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/services/NetworkService.kt
> +class NetworkService : PersistentStateComponent<NetworkService.ClientState>, Disposable {
Можно явно вынести интерфейс взаимодействия с сервером. Тогда, например, можно будет тестировать плагин без использования сети.

2021-05-22 08:54 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/services/NetworkService.kt
> +    class ClientState {
Можно сделать `data class`. Поля лучше все-таки сделать не по-умолчанию, потому что в этом случае легко  забыть передать какой-то параметр, и объект получится неправильным. С дефолтными параметрами объект создается один раз - можно там и передать эти "дефолтные" значения. Еще вместо них можно делать объект `object Unauthorized: ClientState(isSignedIn = false, ...)`, но в нашем случае кажется лишним.

2021-05-22 08:54 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/toolWindow/GameToolWindow.kt
> +class GameToolWindow(project: Project) {
Давай попробуем тулвиндоу сделать вертикальным, а не горизонтальным. Тогда будет видно большую часть эвент-лога. + наши таблицы растут вниз, а не в стороны.

2021-05-22 08:54 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/toolWindow/GameToolWindow.kt
> +    private val toolWindowID = "Feature Registry"
Все-таки к feature registry это тул-виндоу никакого отношения не имеет :) Можно назвать `IDE Gamification`, или `Gamify` или `My progress`, либо `Features`. Либо придумать что-то еще :)

2021-05-22 08:54 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/toolWindow/GameToolWindow.kt
> +            toolWindow = toolWindowManager.registerToolWindow(toolWindowID, true, ToolWindowAnchor.BOTTOM)
Метод `com.intellij.openapi.wm.ToolWindowManager#registerToolWindow(java.lang.String, boolean, com.intellij.openapi.wm.ToolWindowAnchor)` помечен deprecated и его лучше не использовать. В описании причины указан предпочтительный способ - через extension point, либо `ToolWindowFactory`.

2021-05-28 11:06 UTC, bibaev requested changes

2021-05-28 11:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/actions/GameStatisticsDialog.kt
> +            progress1.foreground =
Тут copy-paste для вычисления цвета. Может быть, вынесем в отдельный метод?

2021-05-28 11:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/actions/GameStatisticsDialog.kt
> +        progress1.foreground = Color(kotlin.math.abs(a), kotlin.math.abs(b).toInt(), kotlin.math.abs(c).toInt())
Воу! Тут происходит магия :) Может быть определим более строгая правила для отбора цветов? Например, сделаем список тех, которые нам кажутся подходящими и будем случайно выбирать среди них. Иначе есть вероятность, что цвета будут слишком странными и/или плохо контрастировать с текстом.

2021-06-02 15:56 UTC, bibaev requested changes
Предыдущие замечания все еще актуальны :)

2021-06-02 15:56 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/services/network/KtorClientImpl.kt
> +            httpClient.get("$url/users/$name") // is it ok to put data in url ?
Если мы можем гарантировать, что там не появится странных символов, то да, вполне. :)

2021-06-02 15:56 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/toolWindow/MainFrame.kt
> +class MainFrame(project: Project) : JFrame() {
Этот класс нам точно все еще нужен?

2021-06-03 23:38 UTC, turovkv commented
Кстати, а нормальная ли у нас структура пакетов, или лучше как то исправить?

2021-06-17 10:43 UTC, merged