Demo version of gamification plugin
turovkv/jetbrains-ide-features-gamification pull request #6
Opened 2021-05-04 13:43 UTC by turovkv

2021-05-05 13:06 UTC, bibaev requested changes

2021-05-05 13:06 UTC, bibaev commented on src/main/resources/META-INF/plugin.xml
> +        <group id="com.github.turovkv" text="HelloWorld" popup="true">
Кажется, декларация группы лишняя при создании action.

2021-05-05 13:06 UTC, bibaev commented on src/main/resources/META-INF/plugin.xml
> +            <action id="action.FutureGamificationButton"
~~Future~~FeatureGamification ?

2021-05-05 13:06 UTC, bibaev commented on src/main/resources/META-INF/plugin.xml
> +    <name>Jetbrains-Ide-Features-Gamification</name>
Это имя отображается в списке плагинов и его видят пользователи. Поэтому лучше сделать его более human-friendly. Придумать совсем хорошее имя довольно сложно, но для начала можно назвать так, чтобы это отражало суть и не было перегружено. Например, `Gamification`, `Gamify`, `Learn IDE by game`, etc.

2021-05-05 13:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/services/SavedStatistics.kt
> +    var saved = RewardStatistics()
Лучше `state` делать приватным, чтобы не было возможности влиять на его состояние снаружи сервиса. А все манипуляции с его состоянием делать внутри этого сервиса. Сам state не должен иметь сложной логики - его задача быть контейнером, и, возможно, поддерживать свой инварианты при модификациях.

2021-05-05 13:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/services/SavedStatistics.kt
> +        fun get() = service<SavedStatistics>().state
Обычно `state` не используют сам по себе, а через сервис. То есть лучше сделать `getInstance() -> SavedStatistics` и манипулировать внутренним состоянием через публичные методы сервиса. Сам сервис лучше переименовать. То что он сохраняется это деталь его реализации, а не основное поведение. Его основная ответственность - следить за использованиями фичей.

2021-05-05 13:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/listeners/GameEventListener.kt
> +    fun levelChanged() {}
Обычно, внутри методов listener'ов хочется узнать не только, сам факт, что что-то изменилось, но и новые значения. Поэтому можно сразу передать `int newLevel` как параметр.

Однако, можно сделать более гибко. Помимо `newLevel` мы можем захотеть в будущем передать массу всего дополнительно (количество очков на следующем уровне, использование какой фичи привело к повышению уровня и т.д.). Поэтому можно передавать сразу инстанс класса `GameEvent(val level, val points)`. Тогда если мы захотим передать что-то еще, достаточно будет изменить `GameEvent`, и не трогать все классы, наследующие `GameEventListener`.

2021-05-05 13:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/actions/FeatureGamificationButton.kt
> +class ProgressBar : JFrame() {
Имя вводит в заблуждение. Все-таки там внутри много всего помимо progress bar. Я бы назвал это `GamePanel`, например.

2021-05-05 13:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/actions/FeatureGamificationButton.kt
> +    private class ProgressWorker(private val progress: JProgressBar) : SwingWorker<Void?, Int?>() {
Это совсем лишнее. Указать количество процентов в прогресс баре можно сразу после его создания без создания worker'ов.

2021-05-05 13:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/actions/FeatureGamificationButton.kt
> +    val contentPane: JPanel
Все поля, которые могут быть приватными лучше делать такими. Тогда состояние класса может изменяться только им самим и будет гораздо проще поддерживать его инварианты.

2021-05-05 13:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/actions/FeatureGamificationButton.kt
> +        defaultCloseOperation = HIDE_ON_CLOSE
А правда, что без этого ничего не работает? Подобные вызовы совсем неочевидные и лучше пояснять, почему стандартное поведение нас не устраивает.

2021-05-05 13:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/actions/FeatureGamificationButton.kt
> +class ProgressBar : JFrame() {
Ну и лучше наследовать подобные окошки не от `JFrame`, а от `DialogWrapper`. В нем уже содержится много базовой логики и он гарантировано будет вести себя так же как в другие компоненты в IDE.

2021-05-05 13:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/RewardStatistics.kt
> +data class RewardLogItem(var featureName: String, var points: Int)
Кажется, что `LogItem` подразумевает timestamp внутри.

2021-05-05 13:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/RewardStatistics.kt
> +        return pointsPerFeature.map {
Кажется, это не совсем лог. Лог это скорее что-то такое 
```
в 10:32 ваш уровень увеличился до 2
в 10:30 вы использовали фичу Code completion и получили 100 очков
и т.д.
```

2021-05-05 13:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/RewardStatistics.kt
> +        return pointsPerFeature.map {
Тут же стоит подумать, как нам гарантировать, что лог не станет слишком большим. Например, хранить только за последний месяц, либо не более 1000 записей.

2021-05-05 13:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/RewardStatistics.kt
> +    val rewardStatisticsPublisher =
Кажется, наши эвенты случаются довольно редко, поэтому необходимости кэшировать этот объект нет. Лучше просить каждый раз заново. В теории, может оказаться так, что это каждый раз разный объект и кешировать его вообще нельзя.

2021-05-05 13:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/RewardStatistics.kt
> +    val pointsInLevel: Int = 400
Кажется, это не должно храниться внутри нашего состояния - поскольку это поведение, а не данные. Я бы предложил вынести логику для определения награды за каждое использование и количество очков для получения следующего уровня в отдельный интерфейс `GameMechanics`. Тогда это будет в одном месте и будет удобно.

2021-05-05 13:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/RewardStatistics.kt
> +    fun getProgress() = (100 * (allPoints % pointsInLevel)) / pointsInLevel
У нас нет гарантии, что очком на каждом уровне будет одинаковое количество. Кажется, лучше знать сколько их на текущем и сколько набрано с момента получения нового уровня.

2021-05-05 13:06 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/RewardStatistics.kt
> +    fun clear() {
По-возможности лучше избегать методов `clear()` в пользу создания новых инстансов. Тогда, при добавлении новых полей в класс не нужно постоянно помнить о том, что их нужно занулять в `clear`.

То есть можно вызвать `clear()` у сервиса и уже внутри сделать `saved = new RewardStatistics()`

2021-05-07 15:01 UTC, bibaev requested changes

2021-05-07 15:01 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/actions/FeatureGamificationButton.kt
> +        EventQueue.invokeLater {
`actionPerformed` вызывается уже в UI-потоке, поэтому можно обойтись без `invokeLater`. 

Кстати, если хочется использовать `invokeLater`, лучше использовать `com.intellij.openapi.application.Application#invokeLater(java.lang.Runnable)`. Утверждается, что этот вызов знает про модальность диалогов - https://plugins.jetbrains.com/docs/intellij/general-threading-rules.html#modality-and-invokelater

2021-05-07 15:01 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/PluginState.kt
> +data class GameEvent(val level: Int, val points: Int)
Why not put the event next to a listener declaration? :)

2021-05-07 15:01 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/actions/FeatureGamificationButton.kt
> +class FeatureGamificationButton : AnAction() {
The action doesn't contain complicated logic to work with indices. Thus it might be marked with interface `DumbAware`. Thus the action can be triggered before indexing finishes

2021-05-07 15:01 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/PluginState.kt
> +class PluginState {
`PluginState` выглядит слишком обще. Я бы предложил перенести его в `RewardStatisticsService`, поскольку вне него этот класс не должен использоваться.

2021-05-07 15:01 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/config/Config.kt
> +object Logic {
Кажется, можно обойтись без этого контейнера для констант. А все константы положить прямо в `com.intellij.plugin.gamification.GameMechanicsImpl`

2021-05-07 15:01 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/GameMechanicsImpl.kt
> +    override fun getPointsForEvent(eventName: String, state: PluginState): Int {
`PluginState` слишком сильно мутируемый объект и его лучше держать внутри `com.intellij.plugin.gamification.services.RewardStatisticsService` и никуда не выпускать - это вспомогательный класс, чтобы обеспечить сохраняемость прогресса и не более. Вместо `PluginState` лучше сразу передать количество использований. А почему `eventName`, а не `featureName`?

2021-05-08 16:05 UTC, bibaev requested changes

2021-05-08 16:05 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/actions/ShowGameStatisticsDialog.kt
> +class ShowGameStatisticsDialog(project: Project?) : DialogWrapper(project, true) {
No need to add `Show` prefix to the dialog name since the only purpose of dialog is to be shown :)

2021-05-08 16:05 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/config/Config.kt
> +        const val with = 400
Since the constants are used only inside the single dialog it's better to hide them all as its static (companion object's) fields.

2021-05-08 16:05 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/config/Config.kt
> +        const val with = 400
Also, overriding `getDimensionServiceKey` method from `DialogWrapper` makes dialog to remember location and size of dialog between showings and IDE restarts.

2021-05-08 16:05 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/mechanics/GameMechanicsImpl.kt
> +    companion object {
Might be `private`

2021-05-08 16:05 UTC, bibaev commented on src/main/resources/META-INF/plugin.xml
>      <id>com.github.turovkv.jetbrainsidefeaturesgamification</id>
Let's simplify the id :)

2021-05-08 19:16 UTC, turovkv commented on src/main/kotlin/com/intellij/plugin/gamification/actions/ShowGameStatisticsDialog.kt
> +class ShowGameStatisticsDialog(project: Project?) : DialogWrapper(project, true) {
Сделал по аналогии с  ShowFeatureUsageStatisticsDialog.
Исправил

2021-05-08 20:06 UTC, turovkv commented
![Screenshot from 2021-05-08 23-02-31](https://user-images.githubusercontent.com/57792788/117552067-01dd0180-b052-11eb-9e46-04bddb7dea3a.png)

2021-05-09 09:47 UTC, bibaev requested changes

2021-05-09 09:47 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/actions/GameStatisticsDialog.kt
> +        clearButton.addActionListener {
Сейчас очистка прогресса никак не перерисовывает виджет. Кажется, очистка прогресса - это обычное изменение, поэтому можно просто уведомить всех listener'ов и виджет тоже обновится.

2021-05-09 09:47 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/widget/GameProgressWidgetFactory.kt
> +                        panel.updateState(event)
Лучше, чтобы `panel` сама определяла, когда ей переписываться. Я бы перенес добавление этого listener'a в конструктор GameProgressPanel

2021-05-09 09:47 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/widget/GameProgressPanel.kt
> +        object : ClickListener() {
А установку этого лисенера лучше вынести наружу в `com.intellij.plugin.gamification.widget.GameProgressWidgetFactory#createWidget`. Поскольку "открыть диалог при нажатии" - это уже поведение виджета, а не панели. 
К тому же там и проект уже есть :)

2021-05-09 09:47 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/widget/GameProgressWidgetFactory.kt
> +                GameEventListener.TOPIC,
Получилась довольно сложная конструкция для добавления listener'ов. К тому же, мы раскрываем, что лисенеры добавляются при помощи топиков - а это не единственный способ, и мы можем захотеть его заменить. Если добавить метод `addListener(GameEventListener)` в `com.intellij.plugin.gamification.services.RewardStatisticsService`, то мы спрячем детали реализации и сделаем код клиентов чище.

2021-05-09 09:47 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/widget/GameProgressPanel.kt
> +        size.width = WIDTH // ???
А не получится указать ширину только в конструкторе, а не на каждый `paintComponent`?

2021-05-09 09:47 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/mechanics/GameMechanics.kt
> +    fun getProgress(pointsOnLevel: Int, level: Int): Int
А правда, что этот метод нужен? Вроде это рассчитывается снаружи этого класса, если взять `pointsOnLevel` и `maxPointsOnLevel(level)`

2021-05-09 09:47 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/widget/GameProgressWidgetFactory.kt
> +        ApplicationManager
Тут есть проблема - виджет создается для каждого проекта отдельный. Но listener вешается на уровне приложения. Поэтому при закрытии одного проекта visitor останется висеть в памяти и будет получать уведомления. Во-первых, это утечка памяти. Во-вторых, `panel` может оказаться не готова к таким нотификациям после закрытия и начать бросать исключения. Поэтому при dispose виджета нужно удалять и `listener`. Обычно, такое достигается при помощи `Disposable` и `Disposer`. Например, так - `com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl#addEditorMouseMotionListener(com.intellij.openapi.editor.event.EditorMouseMotionListener, com.intellij.openapi.Disposable)`. В этом случае придется заменить механизм лисенеров с топиков на `com.intellij.util.EventDispatcher`.

2021-05-09 13:48 UTC, turovkv commented on src/main/kotlin/com/intellij/plugin/gamification/widget/GameProgressPanel.kt
> +        size.width = WIDTH // ???
По-моему ширина меняется при присваивании полю text новой строки (и зависит от длины строки). А эта строчка ни на что не влияет. 
Что с этим делать пока не знаю

2021-05-09 17:41 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/widget/GameProgressPanel.kt
> +        size.width = WIDTH // ???
Если эта строчка не влият, может её просто удалить ?:)

2021-05-09 20:06 UTC, turovkv commented on src/main/kotlin/com/intellij/plugin/gamification/widget/GameProgressWidgetFactory.kt
> +        ApplicationManager
Попробовал исправить без EventDispatcher-а

2021-05-10 08:50 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/widget/GameProgressWidgetFactory.kt
> +        ApplicationManager
С таким подходом есть проблемы - часть listener'ов может оказаться подписанными на application, часть на проект. При этом у нас в `plugin.xml` добавляются lintener для application. Как минимум, неочевидно как он будет себя вести. Я бы все-таки ради единообразия предложил сделать через `EventDispatcher`.  

В остальном всё хорошо :)

2021-05-12 00:10 UTC, turovkv commented on src/main/kotlin/com/intellij/plugin/gamification/widget/GameProgressWidgetFactory.kt
> +        ApplicationManager
![Screenshot from 2021-05-12 03-00-07](https://user-images.githubusercontent.com/57792788/117899092-1a0d8480-b2cf-11eb-9f83-56baaa227dd5.png)
как на FeatureUsageListener повлияло добавление EventDispatcher пока что для меня загадка

2021-05-12 10:28 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/services/RewardStatisticsService.kt
> +    private val gameEventListener = EventDispatcher.create(
`gameEventListener` -> `gameEventDispatcher`

2021-05-12 10:28 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/services/RewardStatisticsService.kt
> +    fun addListener(listener: GameEventListener, project: Project) {
Не факт, что все listener'ы будут жить хотя бы столько же времени сколько и проект. Ну и всегда лучше использовать как можно более общий тип. Поэтому тут можно принимать не `Project`, а `Disposable`. 

Кстати, в случае диалога проект передавать неправильно. Диалог закроется раньше проекта. Лучше использовать `getDisposable()` из `DialogWrapper`

2021-05-12 10:28 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/widget/GameProgressWidgetFactory.kt
> +        ApplicationManager
А у меня все работает и нет такой ошибки. Проверь, что лишних изменений в твоем локальном changelist нет.

2021-05-12 10:30 UTC, bibaev commented on src/main/kotlin/com/intellij/plugin/gamification/actions/GameStatisticsDialog.kt
> +    private fun stats() = RewardStatisticsService.getInstance()
Я бы избавился от этого метода. Все его вызовы происходят внутри одного метода. Можно в начале метода получить инстанс сервиса, и потом использовать это локальную переменную.

2021-05-14 11:36 UTC, bibaev approved these changes

2021-05-14 11:37 UTC, merged