Implement a server !
turovkv/jetbrains-ide-features-gamification pull request #9
Opened 2021-05-20 23:11 UTC by turovkv

Любые замечания и предложения приветствуются!

2021-05-22 08:35 UTC, bibaev requested changes

2021-05-22 08:35 UTC, bibaev commented on server/gradlew.bat
> +@if "%DEBUG%" == "" @echo off
Кажется, достаточно иметь файлы `gradlew`/`gradlew.bat` только в самом верхнем проекте.

2021-05-22 08:35 UTC, bibaev commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +    override fun addEmptyUser(credential: UserPasswordCredential): Int = lockOnAdd.withLock {
`Empty` == `New`? Если да, то можно заменить на классическое `createUser` или `registerUser` :)

2021-05-22 08:35 UTC, bibaev commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +    override fun deleteUser(id: Int): Unit = withUserWriteLock(id) {
Мне кажется, можно и не удалять пользователей :) Тогда в UI не придется добавлять новые кнопки

2021-05-22 08:35 UTC, bibaev commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +class InMemoryGamifyRepository : GamifyRepository {
Кажется, что стоит написать тесты, использующие только интерфейс. Но тестировать эту реализацию. Тогда если захотим переехать на другое хранилище тесты уже будут)

2021-05-22 08:35 UTC, bibaev commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +    private val users: MutableMap<Int, User> = ConcurrentHashMap(
Предзаполненный таким образом репозиторий выглядит странно. Лучше в пустой репозиторий добавить этих пользователей уже после создания. Тогда будет меньше вероятность ошибиться и забыть, про какой-то инвариант.

2021-05-22 08:35 UTC, bibaev commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +            0 to ReentrantReadWriteLock(),
Я не очень пониманию, почему нужно по одному локу на каждого пользователя. Разве недостаточно одного на всех?

2021-05-22 08:35 UTC, bibaev commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +            "0" to digestFunction("0"),
Это что кэш для хэш функции?) Это точно преждевременная оптимизация. Давай считать, что вычисление хеш-функции дешевой операцией

2021-05-22 08:35 UTC, bibaev commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +    override fun getIdByName(name: String): Int {
Я бы предложил для упрощения пока делать full-scan по пользователям, чтобы не плодить мапки.

2021-05-22 08:35 UTC, bibaev commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +    private val hashedPaswords: MutableMap<String, ByteArray> = ConcurrentHashMap(
Сейчас репозиторий получился излишне сложным, с кучей структур данных внутри, у которых сложно поддерживать инварианты. Предлагаю максимально упростить и просто хранить список пользователей (возможно, обернутых в объекты с дополнительной мета-информацией, такой как пароли). Если будет втыкать, просто придумаем кэши для медленных запросов. Сейчас у нас получилось как-то слишком сложно и дальше будет большой оверхед на модификацию этого кода.

2021-05-22 08:35 UTC, bibaev commented on server/src/main/kotlin/routes/BasicRoutes.kt
> +fun Route.basicRouting(repository: GamifyRepository) {
`private`?

2021-05-22 08:35 UTC, bibaev commented on server/src/main/kotlin/routes/BasicRoutes.kt
> +        post("") {
Что такое добавить пустого пользователя?) Зачем это может понадобиться?

2021-05-22 08:35 UTC, bibaev commented on server/src/main/kotlin/routes/NotificationRoutes.kt
> +fun Route.notificationRouting(repository: GamifyRepository) {
private?

2021-05-22 08:35 UTC, bibaev commented on server/src/main/kotlin/repository/GamifyRepository.kt
> +    // authorised
Кроме этого комментария никаких гарантий, что авторизация была получена не случилось. Может вынесем их более явно в отдельный интерфейс? Например, чтобы использования выглядели, например, так `repository.authenticate(credintials) {
  deleteUser(id)
}`

2021-05-22 08:35 UTC, bibaev commented on build.gradle.kts
> +        jcenter()
`jCenter` уже deprecated, его можно безопасно удалить

2021-05-22 08:35 UTC, bibaev commented on gradle.properties
> +pluginGroup = gamify
Тут все же лучше указать что-то более уникальное. Хотя бы, как id плагина `intellij.gamify`

2021-05-22 08:35 UTC, bibaev commented on gradle.properties
> +pluginName = gamify
Имя отображается на странице плагина и должно быть с большой буквы

2021-05-22 22:50 UTC, turovkv commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +    private val hashedPaswords: MutableMap<String, ByteArray> = ConcurrentHashMap(
![image](https://user-images.githubusercontent.com/57792788/119242721-07b20700-bb69-11eb-8ff0-706aa20d6f7a.png)

but ok

2021-05-22 22:56 UTC, turovkv commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +            0 to ReentrantReadWriteLock(),
хотелось, чтобы write операции можно было параллельно для разных пользователей делать..

2021-05-23 18:33 UTC, turovkv commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +            "0" to digestFunction("0"),
hashedPaswords это user name -> password hash
переименовал в usersHashedPasswords

2021-05-23 19:29 UTC, turovkv commented on server/src/main/kotlin/repository/GamifyRepository.kt
> +    // authorised
Неочень понимаю, как это сделать(
Я юзаю ```authenticate("my-auth") {...}``` из Ktor [вот ссылка](https://ktor.io/docs/authentication.html). Эта штука автоматически принимает credentials от клиента и чекает пароль с помощью отдельной мапы (которую нужно самому создать, у меня это usersHashedPasswords). И на клиенте есть подобная конструкция для передачи credentials [вот](https://ktor.io/docs/features-auth.html).  Так что у меня нет прямого доступа к credintials.

2021-05-24 20:11 UTC, bibaev commented on server/src/main/kotlin/repository/GamifyRepository.kt
> +    // authorised
И правда все оказалось немного сложнее. Я попробовал поэкспериментировать. Получилось что-то такое - 
[example.patch.zip](https://github.com/turovkv/jetbrains-ide-features-gamification/files/6534732/example.patch.zip). В целом не выглядит как упрощение, но по типам получается немного безопаснее. В нескольких местах до конца уже доводить не стал, но там понятно чего надо сделать. Если понравится, можно накатить эти изменения.

2021-05-24 20:15 UTC, bibaev requested changes

2021-05-24 20:15 UTC, bibaev commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +    private fun getUserById(id: Int): User {
Кажется, что имя пользователя это уже и есть id при нашем способе авторизации. Может быть, будем прямо его и использовать, а не создавать еще один? :)

2021-05-24 20:15 UTC, bibaev commented on server/src/main/kotlin/routes/BasicRoutes.kt
> +        get("{id}") {
Почти все обработчики запросов имеют одну и ту же структуру - сначала проверяется, что указан id, потом обращение к репозиторий внутри try-catch. Может быть вынесем copy-paste в общее место ?:)

2021-05-24 21:27 UTC, turovkv commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +    private fun getUserById(id: Int): User {
В базах данных разве не по id (который Long например) все делается? Реализовал так только для этого..

2021-05-25 06:56 UTC, bibaev commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +    private fun getUserById(id: Int): User {
У нас все-таки пока не база данных :) А небольшое in-memory хранилище. В целом, даже в базе данных использовать целочисленный primary key не обязательно, особенно, когда есть другая сущность, имеющая свойства уникального идентификатора. Числа удобно использовать когда подходящего свойства нет. Ну и из соображений performance лучше использовать числа. Но у нас пока таких проблем нет :)
https://stackoverflow.com/questions/4466553/use-of-an-id-in-databases - вот тут вроде довольно разумное объяснение на этот счет.

2021-05-25 13:30 UTC, turovkv commented on server/src/main/kotlin/repository/GamifyRepository.kt
> +    // authorised
А этот код запускался?
Я не смог починить исключение при запуске сервера((
https://github.com/turovkv/jetbrains-ide-features-gamification/tree/auth-patch
проблема в com.intellij.gamify.server.routes.AuthKt#authenticateByHash

2021-05-26 23:35 UTC, turovkv commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +    private val hashedPaswords: MutableMap<String, ByteArray> = ConcurrentHashMap(
то есть оставить вообще только один контейнер (можно хештаблицу надеюсь) и там в юзере и хеш пароля и локи и все остальное?

2021-05-26 23:37 UTC, turovkv commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +            0 to ReentrantReadWriteLock(),
можно так оставить или нужно один лок на весь репозиторий?

2021-05-27 09:15 UTC, bibaev requested changes

2021-05-27 09:15 UTC, bibaev commented on server/src/main/kotlin/repository/GamifyRepository.kt
> +        fun unsubscribe(nameTo: String)
`unsubscribe from`? I mean renaming parameter name `nameTo` -> `nameFrom`

2021-05-27 09:15 UTC, bibaev commented on server/src/main/kotlin/routes/auth.kt
> +        println("HELLO :(")
Думаю, теперь можно удалить это пессимизм при каждом запуске :)

2021-05-27 09:15 UTC, bibaev commented on server/src/main/kotlin/routes/NotificationRoutes.kt
> +//        get("subscribing/{name}") {
Давай стараться очень избегать закомментированного кода. Если он нам понадобится, то он всегда есть в VCS. А так он лежит и вызывает лишние  вопросы и эмоции :)

2021-05-27 09:15 UTC, bibaev commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +    private val hashedPaswords: MutableMap<String, ByteArray> = ConcurrentHashMap(
Ага. Необязательно именно в юзере. Мне кажется, лучше чтобы юзер не знал ни про логи, ни про нотификации, поэтому лучше сделать отдельный класс для этого.

2021-05-27 09:15 UTC, bibaev commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +            0 to ReentrantReadWriteLock(),
Мне кажется, что можно обойтись одним глобальным локом (либо без них вовсе, раз уж у нас останется одна мапка, у которой мы модифицируем отдельные элементы и иногда добавляем/удаляем - тогда можно обойтись concurrent мапкой без дополнительной синхронизации)

2021-05-27 15:05 UTC, turovkv commented on server/src/main/kotlin/repository/InMemoryGamifyRepository.kt
> +            0 to ReentrantReadWriteLock(),
как без синхронизации, если при запросе getNotifications юзер смотрит на других юзеров, на которых подписался. И в этот момент один из них мог сделать addNotification. Получается одновременно и пишем и читаем....

2021-05-28 07:44 UTC, bibaev approved these changes

2021-05-28 09:14 UTC, merged